// frontend/archive/admin-react/src/pages/user/PatientList.tsx
import { useState, useEffect, useCallback } from 'react'
import { Input, Button, Icon } from 'semantic-ui-react'
import DataTable, { type Column } from '../../components/DataTable'
import FormModal from '../../components/FormModal'
import StatusTag from '../../components/StatusTag'
import { userApi } from '../../api/user'
import type { Patient, PageData } from '../../api/types'

export default function PatientList() {
  const [data, setData] = useState<PageData<Patient>>()
  const [loading, setLoading] = useState(false)
  const [page, setPage] = useState(1)
  const [modalOpen, setModalOpen] = useState(false)
  const [editing, setEditing] = useState<Partial<Patient> & { id?: string }>({})

  const fetch = useCallback(async () => {
    setLoading(true)
    try {
      const res = await userApi.getPatients({ page, pageSize: 10 })
      setData(res)
    } catch { /* error shown in client interceptor */ }
    finally { setLoading(false) }
  }, [page])

  useEffect(() => { fetch() }, [fetch])

  const columns: Column<Patient>[] = [
    { key: 'name', header: '姓名', render: (r) => r.name },
    { key: 'gender', header: '性别', render: (r) => r.gender },
    { key: 'age', header: '年龄', render: (r) => r.age },
    { key: 'phone', header: '电话', render: (r) => r.phone },
    { key: 'idCard', header: '身份证', render: (r) => r.idCard },
    { key: 'address', header: '地址', render: (r) => r.address },
    {
      key: 'actions', header: '操作', render: (r) => (
        <Button.Group size="small">
          <Button icon="edit" onClick={() => { setEditing(r); setModalOpen(true) }} />
          <Button icon="trash" color="red" onClick={async () => {
            if (confirm('确认删除？')) { await userApi.deletePatient(r.id); fetch() }
          }} />
        </Button.Group>
      ),
    },
  ]

  return (
    <>
      <DataTable
        columns={columns}
        data={data}
        loading={loading}
        onPageChange={setPage}
        onCreate={() => { setEditing({}); setModalOpen(true) }}
        createLabel="新增患者"
      />
      <FormModal
        open={modalOpen}
        title={editing.id ? '编辑患者' : '新增患者'}
        initialValues={{ name: editing.name || '', gender: editing.gender || '', age: String(editing.age || ''), phone: editing.phone || '', idCard: editing.idCard || '', address: editing.address || '' }}
        fields={[
          { key: 'name', label: '姓名', required: true, render: (v, onChange) => <Input value={v} onChange={(_, d) => onChange(d.value)} placeholder="姓名" /> },
          { key: 'gender', label: '性别', required: true, render: (v, onChange) => <Input value={v} onChange={(_, d) => onChange(d.value)} placeholder="男/女" /> },
          { key: 'age', label: '年龄', required: true, render: (v, onChange) => <Input value={v} onChange={(_, d) => onChange(d.value)} type="number" placeholder="年龄" /> },
          { key: 'phone', label: '电话', render: (v, onChange) => <Input value={v} onChange={(_, d) => onChange(d.value)} placeholder="电话" /> },
          { key: 'idCard', label: '身份证', render: (v, onChange) => <Input value={v} onChange={(_, d) => onChange(d.value)} placeholder="身份证" /> },
          { key: 'address', label: '地址', render: (v, onChange) => <Input value={v} onChange={(_, d) => onChange(d.value)} placeholder="地址" /> },
        ]}
        onSubmit={async (vals) => {
          const payload = { ...vals, age: parseInt(vals.age) || 0 }
          if (editing.id) await userApi.updatePatient(editing.id, payload)
          else await userApi.createPatient(payload)
          fetch()
        }}
        onClose={() => setModalOpen(false)}
      />
    </>
  )
}

// frontend/admin/src/views/user/PatientList.vue
<template>
  <div>
    <a-card title="患者管理">
      <template #extra>
        <a-space>
          <a-input-search
            v-model:value="searchName"
            placeholder="搜索患者姓名"
            style="width: 200px"
            @search="fetchData"
          />
          <a-button type="primary" @click="showCreateModal">
            <PlusOutlined /> 新增患者
          </a-button>
        </a-space>
      </template>
      <a-table
        :columns="columns"
        :data-source="dataSource"
        :loading="loading"
        :pagination="pagination"
        row-key="id"
        @change="onTableChange"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'gender'">
            {{ genderMap[record.gender] || record.gender }}
          </template>
          <template v-if="column.key === 'action'">
            <a-space>
              <a @click="viewDetail(record)">详情</a>
              <a @click="editRecord(record)">编辑</a>
              <a-popconfirm title="确认删除？" @confirm="deleteRecord(record.id)">
                <a style="color: red">删除</a>
              </a-popconfirm>
            </a-space>
          </template>
        </template>
      </a-table>
    </a-card>

    <a-modal v-model:open="modalOpen" :title="modalTitle" @ok="handleSubmit" :confirm-loading="submitting">
      <a-form :model="formState" layout="vertical">
        <a-form-item label="姓名" required>
          <a-input v-model:value="formState.name" />
        </a-form-item>
        <a-form-item label="性别">
          <a-select v-model:value="formState.gender">
            <a-select-option value="M">男</a-select-option>
            <a-select-option value="F">女</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="手机号">
          <a-input v-model:value="formState.phone" />
        </a-form-item>
        <a-form-item label="身份证号">
          <a-input v-model:value="formState.idCard" />
        </a-form-item>
        <a-form-item label="地址">
          <a-input v-model:value="formState.address" />
        </a-form-item>
      </a-form>
    </a-modal>

    <a-modal v-model:open="detailOpen" title="患者详情" :footer="null" width="600px">
      <a-descriptions v-if="detailRecord" :column="2" bordered size="small">
        <a-descriptions-item v-for="(v, k) in detailRecord" :key="k" :label="k">{{ v }}</a-descriptions-item>
      </a-descriptions>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import { PlusOutlined } from '@ant-design/icons-vue'
import { userApi } from '@/api/user'
import { genderMap } from '@/utils'

const loading = ref(false)
const searchName = ref('')
const dataSource = ref<any[]>([])
const modalOpen = ref(false)
const detailOpen = ref(false)
const detailRecord = ref<any>(null)
const modalTitle = ref('新增患者')
const submitting = ref(false)
const isEdit = ref(false)

const pagination = reactive({
  current: 1,
  pageSize: 10,
  total: 0,
})

const formState = reactive({
  id: '',
  name: '',
  gender: 'M',
  phone: '',
  idCard: '',
  address: '',
})

const columns = [
  { title: '姓名', dataIndex: 'name', key: 'name' },
  { title: '性别', key: 'gender' },
  { title: '手机号', dataIndex: 'phone', key: 'phone' },
  { title: '身份证号', dataIndex: 'idCard', key: 'idCard' },
  { title: '创建时间', dataIndex: 'createdAt', key: 'createdAt' },
  { title: '操作', key: 'action', width: 200 },
]

async function fetchData() {
  loading.value = true
  try {
    const res: any = await userApi.getPatients({
      page: pagination.current,
      pageSize: pagination.pageSize,
      name: searchName.value || undefined,
    })
    dataSource.value = res?.list || res || []
    pagination.total = res?.total || 0
  } catch {
    dataSource.value = []
  } finally {
    loading.value = false
  }
}

function onTableChange(pag: any) {
  pagination.current = pag.current
  pagination.pageSize = pag.pageSize
  fetchData()
}

function showCreateModal() {
  isEdit.value = false
  modalTitle.value = '新增患者'
  Object.assign(formState, { id: '', name: '', gender: 'M', phone: '', idCard: '', address: '' })
  modalOpen.value = true
}

function editRecord(record: any) {
  isEdit.value = true
  modalTitle.value = '编辑患者'
  Object.assign(formState, record)
  modalOpen.value = true
}

function viewDetail(record: any) {
  detailRecord.value = record; detailOpen.value = true
}

async function deleteRecord(id: string) {
  try {
    await userApi.deletePatient(id)
    message.success('删除成功')
    fetchData()
  } catch { message.error('删除失败') }
}

async function handleSubmit() {
  submitting.value = true
  try {
    if (isEdit.value) {
      await userApi.updatePatient(formState.id, {
        name: formState.name,
        gender: formState.gender,
        phone: formState.phone,
        idCard: formState.idCard,
        address: formState.address,
      })
    } else {
      await userApi.createPatient({
        name: formState.name,
        gender: formState.gender,
        phone: formState.phone,
        idCard: formState.idCard,
        address: formState.address,
      })
    }
    modalOpen.value = false
    message.success(isEdit.value ? '保存成功' : '创建成功')
    fetchData()
  } catch {
    message.error('操作失败')
  } finally {
    submitting.value = false
  }
}

onMounted(fetchData)
</script>
